DO
$do$
BEGIN
   IF
EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = 'devices-management-manager') THEN

          RAISE NOTICE 'Role "devices-management-manager" already exists. Skipping.';
ELSE
CREATE ROLE "devices-management-manager";
END IF;
END
$do$;

CREATE TABLE devices
(
    device_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid uuid UNIQUE                                    NOT NULL,
    device_name text UNIQUE                                    NOT NULL,
    brand_name  text                                           NOT NULL,
    created_at  timestamp DEFAULT timezone('utc'::TEXT, now()) NOT NULL
)
