# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: device-management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Download and Setup GO
        run: |
          sudo apt update
          sudo apt install golang-1.23

      - name: Build
        if: success()
        run: |
          echo "$(pwd)"
          go build -v -buildvcs=false ./...

      - name: Run DB
        if: success()
        id: runDB
        run: |
          echo "$(pwd)"
          make run-ci

      - name: Test
        if: success()
        run: |
          echo "$(pwd)"
          go test -v -buildvcs=false ./...
      - name: Tear Down DB
        if: steps.runDB.conclusion =='success'
        run: |
          echo "$(pwd)"
          make dev-db-docker-delete