# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: device-management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.22.3'
      - name: Run DB
        id: runDB
        run: |
          cd ./...
          echo "$(pwd)"
          make run-ci

      - name: Build
        if: success()
        run: |
          cd ./...
          echo "$(pwd)"
          go build -v -buildvcs=false .

      - name: Test
        if: success()
        run: |
          cd ./...
          echo "$(pwd)"
          go test -v -buildvcs=false .
      - name: Tear Down DB
        if: steps.runDB.conclusion =='success'
        run: |
          cd ./...
          echo "$(pwd)"
          make dev-db-docker-delete