#name: Release
#
#on:
#  push:
#    tags:
#      - "v*"
#jobs:
#  # the workflow can contain other jobs, such as linting, testing, etc.
#  release:
#    runs-on: ubuntu-latest
#    steps:
#      # run git checkout
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Load environment variables
#        uses: dotenv-actions/setup-dotenv@v2
#        with:
#          dotenv_path: ".env"
#
#      # setup go
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{env.GO_VERSION}}
#
#      # run goreleaser
#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v4
#        with:
#          version: latest
#          args: release --rm-dist
#          distribution: goreleaser
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}